---
version: 2
plan:
  project-key: NEW
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!'
    - checkout:
       force-clean-build: 'false'
    - checkout:
       repository: Bamboo
       force-clean-build: 'false'
